{% set name = "pykep" %}
{% set version = "2.6.2" %}
{% set sha256 = "4e298961298b837ba42b98ccaf11639d3230b6e18724a40b7422f9c97af41f6c" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://github.com/esa/pykep/archive/v{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 2
  skip: true  # [(win and py<36) or win32]
  skip: true  # [py2k]

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - {{ compiler('c') }}
    - {{ stdlib("c") }}
    - {{ compiler('cxx') }}
    - cmake
    - make       # [unix]
  host:
    - libboost-python-devel
    - libboost-devel
    - python
  run:
    - python
    - matplotlib-base
    - {{ pin_compatible('numpy') }}
    - scipy

about:
  home: https://esa.github.io/pykep/
  license: GPL v3 and LGPL v3
  license_file: LICENSE.txt
  summary: pykep is a scientific library providing basic tools for interplanetary trajectory design.

extra:
  recipe-maintainers:
    - darioizzo
