{% set name = "pykep" %}
{% set version = "2.2" %}
{% set sha256 = "67a775aca20ccdd8c6ed9e409f42d0dd0e857bd78cda32fc6e632d71dadd721b" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://github.com/esa/pykep/archive/v{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 1000
  skip: true  # [win]

requirements:
  build:
    - cmake
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
  host:
    - boost
    - python

  run:
    - boost
    - python


test:
  commands:
    - test -f
  imports:
    - pykep

about:
  home: https://esa.github.io/pykep/
  license: GPL v3 and LGPL v3
  license_file: LICENSE.txt
  summary: 'pykep is a scientific library providing basic tools for interplanetary trajectory design.'

extra:
  recipe-maintainers:
    - darioizzo
