{% set name = "pykep" %}
{% set version = "2.5" %}
{% set sha256 = "33f5e61f11234d3da4bca9684f2e90f7a39cfb509222b22834cda419b519d844" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://github.com/esa/pykep/archive/v{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  skip: true  # [(win and py<36) or win32]
  skip: true  # [py2k]

requirements:
  build:
    - cmake
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - clang      # [win]
    - ninja      # [win]
  host:
    - boost
    - boost-cpp
    - python
  run:
    - boost
    - boost-cpp
    - python
    - matplotlib
    - numpy
    - scipy

about:
  home: https://esa.github.io/pykep/
  license: GPL v3 and LGPL v3
  license_file: LICENSE.txt
  summary: pykep is a scientific library providing basic tools for interplanetary trajectory design.

extra:
  recipe-maintainers:
    - darioizzo
