{% set name = "pykep" %}
{% set version = "2.4.1" %}
{% set sha256 = "09cdb91c8bb11fda6f8a15dc39c67990016ec8d0755d79db97c83a43a7bd7952" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://github.com/esa/pykep/archive/v{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 1
  skip: true  # [(win and py<36) or win32]

requirements:
  build:
    - cmake
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - clang      # [win]
    - ninja      # [win]
  host:
    - boost
    - boost-cpp
    - python
  run:
    - boost
    - boost-cpp
    - python
    - matplotlib
    - numpy
    - scipy

about:
  home: https://esa.github.io/pykep/
  license: GPL v3 and LGPL v3
  license_file: LICENSE.txt
  summary: 'pykep is a scientific library providing basic tools for interplanetary trajectory design.'

extra:
  recipe-maintainers:
    - darioizzo
