{% set name = "pykep" %}
{% set version = "2.1" %}
{% set sha256 = "601a73cc6090977091ae719e692dd55cc51bde241ba2f156fb06ac1b7130feca" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://github.com/esa/pykep/archive/v{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 1
  skip: true  # [win]

requirements:
  build:
    - cmake
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
  host:
    - boost
    - python

  run:
    - boost
    - python


test:
  commands:
    - test -f
  imports:
    - pykep

about:
  home: https://esa.github.io/pykep/
  license: GPL v3 and LGPL v3
  license_file: LICENSE.txt
  summary: 'pykep is a scientific library providing basic tools for interplanetary trajectory design.'

extra:
  recipe-maintainers:
    - darioizzo
