{% set name = "pykep" %}
{% set version = "2.6" %}
{% set sha256 = "67ba9a45b51ce9e99117621a4901095c5404c7ec285ac58e7782c94f37c65de7" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://github.com/esa/pykep/archive/v{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 3
  skip: true  # [(win and py<36) or win32]
  skip: true  # [py2k]

requirements:
  build:
    - cmake
    - {{ compiler('c') }}   # [not win]
    - {{ compiler('cxx') }}   # [not win]
    - clang      # [win]
    - ninja      # [win]
  host:
    - boost
    - boost-cpp
    - python
  run:
    - {{ pin_compatible("boost", max_pin="x.x") }}
    - {{ pin_compatible("boost-cpp", max_pin="x.x") }}
    - python
    - matplotlib-base
    - {{ pin_compatible('numpy') }}

    - scipy

about:
  home: https://esa.github.io/pykep/
  license: GPL v3 and LGPL v3
  license_file: LICENSE.txt
  summary: pykep is a scientific library providing basic tools for interplanetary trajectory design.

extra:
  recipe-maintainers:
    - darioizzo
